# Generated by Django 4.2.19 on 2025-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "ingredients",
                    models.JSONField(
                        default=list,
                        help_text="List of ingredients as a JSON array (e.g., ['2 eggs', '1 cup sugar']).",
                    ),
                ),
                (
                    "directions",
                    models.JSONField(
                        default=list,
                        help_text="List of steps, each containing 'Active' and 'Passive' keys.",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
